//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramacionAvanzadaG8.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Venta
    {
        public int detalle_venta_id { get; set; }
        public int venta_id { get; set; }
        public int producto_id { get; set; }
        public int cantidad { get; set; }
        public decimal precio_unitario { get; set; }
        public Nullable<decimal> descuento_linea { get; set; }
        public decimal total_linea { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
