

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProgramacionAvanzadaG8.EntityFramework
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class FrijolitoEntities1 : DbContext
{
    public FrijolitoEntities1()
        : base("name=FrijolitoEntities1")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Categoria> Categoria { get; set; }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<Detalle_Venta> Detalle_Venta { get; set; }

    public virtual DbSet<Metodo_Pago> Metodo_Pago { get; set; }

    public virtual DbSet<Pago> Pago { get; set; }

    public virtual DbSet<Producto> Producto { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    public virtual DbSet<Venta> Venta { get; set; }


    public virtual ObjectResult<IniciarSesion_Result> IniciarSesion(string username, string passwordHash)
    {

        var usernameParameter = username != null ?
            new ObjectParameter("Username", username) :
            new ObjectParameter("Username", typeof(string));


        var passwordHashParameter = passwordHash != null ?
            new ObjectParameter("PasswordHash", passwordHash) :
            new ObjectParameter("PasswordHash", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IniciarSesion_Result>("IniciarSesion", usernameParameter, passwordHashParameter);
    }


    public virtual ObjectResult<ObtenerCategorias_Result> ObtenerCategorias()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerCategorias_Result>("ObtenerCategorias");
    }


    public virtual ObjectResult<ObtenerProductoPorId_Result> ObtenerProductoPorId(Nullable<int> productoId)
    {

        var productoIdParameter = productoId.HasValue ?
            new ObjectParameter("ProductoId", productoId) :
            new ObjectParameter("ProductoId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerProductoPorId_Result>("ObtenerProductoPorId", productoIdParameter);
    }


    public virtual ObjectResult<ObtenerProductos_Result> ObtenerProductos(Nullable<int> categoriaId, string genero)
    {

        var categoriaIdParameter = categoriaId.HasValue ?
            new ObjectParameter("CategoriaId", categoriaId) :
            new ObjectParameter("CategoriaId", typeof(int));


        var generoParameter = genero != null ?
            new ObjectParameter("Genero", genero) :
            new ObjectParameter("Genero", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerProductos_Result>("ObtenerProductos", categoriaIdParameter, generoParameter);
    }


    public virtual ObjectResult<Nullable<int>> RegistrarUsuario(string username, string passwordHash, string nombre, string apellido, string email)
    {

        var usernameParameter = username != null ?
            new ObjectParameter("Username", username) :
            new ObjectParameter("Username", typeof(string));


        var passwordHashParameter = passwordHash != null ?
            new ObjectParameter("PasswordHash", passwordHash) :
            new ObjectParameter("PasswordHash", typeof(string));


        var nombreParameter = nombre != null ?
            new ObjectParameter("Nombre", nombre) :
            new ObjectParameter("Nombre", typeof(string));


        var apellidoParameter = apellido != null ?
            new ObjectParameter("Apellido", apellido) :
            new ObjectParameter("Apellido", typeof(string));


        var emailParameter = email != null ?
            new ObjectParameter("Email", email) :
            new ObjectParameter("Email", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("RegistrarUsuario", usernameParameter, passwordHashParameter, nombreParameter, apellidoParameter, emailParameter);
    }

}

}

