//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramacionAvanzadaG8.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int pago_id { get; set; }
        public int venta_id { get; set; }
        public int metodo_pago_id { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public decimal monto { get; set; }
        public string referencia { get; set; }
    
        public virtual Metodo_Pago Metodo_Pago { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
