
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProgramacionAvanzadaG8.EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class Venta
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Venta()
    {

        this.Detalle_Venta = new HashSet<Detalle_Venta>();

        this.Pago = new HashSet<Pago>();

    }


    public int venta_id { get; set; }

    public Nullable<System.DateTime> fecha { get; set; }

    public int cliente_id { get; set; }

    public int usuario_id { get; set; }

    public decimal subtotal { get; set; }

    public decimal impuesto { get; set; }

    public Nullable<decimal> descuento { get; set; }

    public decimal total { get; set; }

    public string estado { get; set; }



    public virtual Cliente Cliente { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Detalle_Venta> Detalle_Venta { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Pago> Pago { get; set; }

    public virtual Usuario Usuario { get; set; }

}

}
